[package]
name = "client_server_communication"
version = "0.1.0"
authors = ["Pavel Kosilo <kodosgames@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
